schema_version = 2

[source]
path = 'D:\.DEV\ingestion-lab\ingestion-lab-loadgen\data\MBD-mini\trx\fold=*\*.parquet'
unit = "glob-pattern"
mutability = "startup-only"

[reader.read_batch_size]
default = 1_000
min = 1_000
max = 100_000
step = 1_000
unit = "transactions"
mutability = "idle-only"

[readerChannel.capacity]
default = 2
allowed = [0, 1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192]
unit = "batches"
mutability = "idle-only"

[senderChannel.capacity]
default = 0
allowed = [0, 1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192]
unit = "batches"
mutability = "idle-only"

[throttler.requested_tps]
default = 2_000
min = 0
max = 4_000
step = 100
unit = "transactions/s"
mutability = "immediate"

[throttler.installation_mode]
default = "installed"
allowed = ["installed", "bypass"]
mutability = "immediate"

[metrics.window_ms]
default = 1_000
min = 100
max = 10_000
step = 100
unit = "milliseconds"
mutability = "startup-only"
